server:
  port: 8080
spring:
  application:
    name: bff-microservice
external:
  api:
    client: http://client-microservice:8081
    product: http://product-microservice:8082
    transaction: http://transaction-microservice:8083
