server:
  port: 8081
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

spring:
  application:
    name: client-microservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/bank