server:
  port: 8080
spring:
  application:
    name: gateway-microservice
  cloud:
    gatewat:
      routes[0]:
        id: bff-bank
        url: http://bff-bank:9090
        predicates[0]: Path=/client/**
