server:
  port: 8080
spring:
  application:
    name: gateway-microservice
  cloud:
    gateway:
      routes:
        - id: bff-bank
          url: http://bff-bank:9090
          predicates: 
            - Path=/client/**
