version: '3.7'
services:
  ms-config-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7070:7070
    networks:
      - servicio_ntt
networks:
  servicio_ntt:
    external: true